name: org.dartlang.dart_roller_dashboard


dependencies:
  cron: ^0.2.1
  bloc: 1.0.0
  flutter_bloc: 1.0.0
  shelf: ^0.7.5
  shelf_static: ^0.2.8
  sse: ^2.0.1
  web_socket_channel: ^1.0.12

dev_dependencies:
  build_runner: any
  build_web_compilers: any

dependency_overrides:
